/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedTrendsImport } from './routes/_authenticated/trends'
import { Route as AuthenticatedLogImport } from './routes/_authenticated/log'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as AuthRoutesSignUpImport } from './routes/_authRoutes/sign-up'
import { Route as AuthRoutesSignInImport } from './routes/_authRoutes/sign-in'
import { Route as AuthRoutesForgotPasswordImport } from './routes/_authRoutes/forgot-password'
import { Route as AuthRoutesAuthFormImport } from './routes/_authRoutes/_auth-form'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTrendsRoute = AuthenticatedTrendsImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLogRoute = AuthenticatedLogImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthRoutesSignUpRoute = AuthRoutesSignUpImport.update({
  id: '/_authRoutes/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoutesSignInRoute = AuthRoutesSignInImport.update({
  id: '/_authRoutes/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoutesForgotPasswordRoute = AuthRoutesForgotPasswordImport.update({
  id: '/_authRoutes/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoutesAuthFormRoute = AuthRoutesAuthFormImport.update({
  id: '/_authRoutes/_auth-form',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authRoutes/_auth-form': {
      id: '/_authRoutes/_auth-form'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRoutesAuthFormImport
      parentRoute: typeof rootRoute
    }
    '/_authRoutes/forgot-password': {
      id: '/_authRoutes/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthRoutesForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_authRoutes/sign-in': {
      id: '/_authRoutes/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthRoutesSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authRoutes/sign-up': {
      id: '/_authRoutes/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthRoutesSignUpImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRoutesAuthFormRoute
  '/forgot-password': typeof AuthRoutesForgotPasswordRoute
  '/sign-in': typeof AuthRoutesSignInRoute
  '/sign-up': typeof AuthRoutesSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/log': typeof AuthenticatedLogRoute
  '/trends': typeof AuthenticatedTrendsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRoutesAuthFormRoute
  '/forgot-password': typeof AuthRoutesForgotPasswordRoute
  '/sign-in': typeof AuthRoutesSignInRoute
  '/sign-up': typeof AuthRoutesSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/log': typeof AuthenticatedLogRoute
  '/trends': typeof AuthenticatedTrendsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authRoutes/_auth-form': typeof AuthRoutesAuthFormRoute
  '/_authRoutes/forgot-password': typeof AuthRoutesForgotPasswordRoute
  '/_authRoutes/sign-in': typeof AuthRoutesSignInRoute
  '/_authRoutes/sign-up': typeof AuthRoutesSignUpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/log'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/log'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authRoutes/_auth-form'
    | '/_authRoutes/forgot-password'
    | '/_authRoutes/sign-in'
    | '/_authRoutes/sign-up'
    | '/_authenticated/dashboard'
    | '/_authenticated/log'
    | '/_authenticated/trends'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoutesAuthFormRoute: typeof AuthRoutesAuthFormRoute
  AuthRoutesForgotPasswordRoute: typeof AuthRoutesForgotPasswordRoute
  AuthRoutesSignInRoute: typeof AuthRoutesSignInRoute
  AuthRoutesSignUpRoute: typeof AuthRoutesSignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoutesAuthFormRoute: AuthRoutesAuthFormRoute,
  AuthRoutesForgotPasswordRoute: AuthRoutesForgotPasswordRoute,
  AuthRoutesSignInRoute: AuthRoutesSignInRoute,
  AuthRoutesSignUpRoute: AuthRoutesSignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/_authRoutes/_auth-form",
        "/_authRoutes/forgot-password",
        "/_authRoutes/sign-in",
        "/_authRoutes/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard",
        "/_authenticated/log",
        "/_authenticated/trends"
      ]
    },
    "/_authRoutes/_auth-form": {
      "filePath": "_authRoutes/_auth-form.tsx"
    },
    "/_authRoutes/forgot-password": {
      "filePath": "_authRoutes/forgot-password.tsx"
    },
    "/_authRoutes/sign-in": {
      "filePath": "_authRoutes/sign-in.tsx"
    },
    "/_authRoutes/sign-up": {
      "filePath": "_authRoutes/sign-up.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/log": {
      "filePath": "_authenticated/log.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/trends": {
      "filePath": "_authenticated/trends.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
