/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewLogRouteImport } from './routes/new-log'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as OrgSlugRouteImport } from './routes/org/$slug'
import { Route as MarketingSsoCallbackRouteImport } from './routes/_marketing.sso-callback'
import { Route as MarketingSignupRouteImport } from './routes/_marketing.signup'
import { Route as MarketingLoginRouteImport } from './routes/_marketing.login'
import { Route as MarketingJoinRouteImport } from './routes/_marketing.join'
import { Route as MarketingGetStartedRouteImport } from './routes/_marketing.get-started'
import { Route as OrgSlugIndexRouteImport } from './routes/org/$slug/index'
import { Route as ApiFlagsIndexRouteImport } from './routes/api/flags/index'
import { Route as OrgSlugNotAMemberRouteImport } from './routes/org/$slug/not-a-member'
import { Route as OrgSlugAuthenticatedRouteImport } from './routes/org/$slug/_authenticated'
import { Route as ApiPolarWebhookRouteImport } from './routes/api/polar/webhook'
import { Route as OrgSlugUnauthenticatedSsoCallbackRouteImport } from './routes/org/$slug/_unauthenticated/sso-callback'
import { Route as OrgSlugUnauthenticatedSignUpRouteImport } from './routes/org/$slug/_unauthenticated/sign-up'
import { Route as OrgSlugUnauthenticatedSignInRouteImport } from './routes/org/$slug/_unauthenticated/sign-in'
import { Route as OrgSlugUnauthenticatedForgotPasswordRouteImport } from './routes/org/$slug/_unauthenticated/forgot-password'
import { Route as OrgSlugAuthenticatedWelcomeRouteImport } from './routes/org/$slug/_authenticated/welcome'
import { Route as OrgSlugAuthenticatedTrendsRouteImport } from './routes/org/$slug/_authenticated/trends'
import { Route as OrgSlugAuthenticatedSettingsRouteImport } from './routes/org/$slug/_authenticated/settings'
import { Route as OrgSlugAuthenticatedLogRouteImport } from './routes/org/$slug/_authenticated/log'
import { Route as OrgSlugAuthenticatedInsightsRouteImport } from './routes/org/$slug/_authenticated/insights'
import { Route as OrgSlugAuthenticatedGoalsRouteImport } from './routes/org/$slug/_authenticated/goals'
import { Route as OrgSlugAuthenticatedDashboardRouteImport } from './routes/org/$slug/_authenticated/dashboard'
import { Route as OrgSlugAuthenticatedCalendarRouteImport } from './routes/org/$slug/_authenticated/calendar'
import { Route as OrgSlugAuthenticatedAdminRouteImport } from './routes/org/$slug/_authenticated/admin'
import { Route as OrgSlugAuthenticatedJournalIndexRouteImport } from './routes/org/$slug/_authenticated/journal/index'
import { Route as OrgSlugAuthenticatedGroupsIndexRouteImport } from './routes/org/$slug/_authenticated/groups/index'
import { Route as OrgSlugAuthenticatedJournalNewRouteImport } from './routes/org/$slug/_authenticated/journal/new'
import { Route as OrgSlugAuthenticatedJournalJournalIdRouteImport } from './routes/org/$slug/_authenticated/journal/$journalId'
import { Route as OrgSlugAuthenticatedGroupsGroupIdRouteImport } from './routes/org/$slug/_authenticated/groups/$groupId'

const NewLogRoute = NewLogRouteImport.update({
  id: '/new-log',
  path: '/new-log',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSsoCallbackRoute = MarketingSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSignupRoute = MarketingSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLoginRoute = MarketingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingJoinRoute = MarketingJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingGetStartedRoute = MarketingGetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => MarketingRoute,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const ApiFlagsIndexRoute = ApiFlagsIndexRouteImport.update({
  id: '/api/flags/',
  path: '/api/flags/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugNotAMemberRoute = OrgSlugNotAMemberRouteImport.update({
  id: '/not-a-member',
  path: '/not-a-member',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugAuthenticatedRoute = OrgSlugAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => OrgSlugRoute,
} as any)
const ApiPolarWebhookRoute = ApiPolarWebhookRouteImport.update({
  id: '/api/polar/webhook',
  path: '/api/polar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugUnauthenticatedSsoCallbackRoute =
  OrgSlugUnauthenticatedSsoCallbackRouteImport.update({
    id: '/_unauthenticated/sso-callback',
    path: '/sso-callback',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugUnauthenticatedSignUpRoute =
  OrgSlugUnauthenticatedSignUpRouteImport.update({
    id: '/_unauthenticated/sign-up',
    path: '/sign-up',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugUnauthenticatedSignInRoute =
  OrgSlugUnauthenticatedSignInRouteImport.update({
    id: '/_unauthenticated/sign-in',
    path: '/sign-in',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugUnauthenticatedForgotPasswordRoute =
  OrgSlugUnauthenticatedForgotPasswordRouteImport.update({
    id: '/_unauthenticated/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugAuthenticatedWelcomeRoute =
  OrgSlugAuthenticatedWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedTrendsRoute =
  OrgSlugAuthenticatedTrendsRouteImport.update({
    id: '/trends',
    path: '/trends',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedSettingsRoute =
  OrgSlugAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedLogRoute = OrgSlugAuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => OrgSlugAuthenticatedRoute,
} as any)
const OrgSlugAuthenticatedInsightsRoute =
  OrgSlugAuthenticatedInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedGoalsRoute =
  OrgSlugAuthenticatedGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedDashboardRoute =
  OrgSlugAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedCalendarRoute =
  OrgSlugAuthenticatedCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedAdminRoute =
  OrgSlugAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedJournalIndexRoute =
  OrgSlugAuthenticatedJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedGroupsIndexRoute =
  OrgSlugAuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedJournalNewRoute =
  OrgSlugAuthenticatedJournalNewRouteImport.update({
    id: '/journal/new',
    path: '/journal/new',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedJournalJournalIdRoute =
  OrgSlugAuthenticatedJournalJournalIdRouteImport.update({
    id: '/journal/$journalId',
    path: '/journal/$journalId',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)
const OrgSlugAuthenticatedGroupsGroupIdRoute =
  OrgSlugAuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => OrgSlugAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/new-log': typeof NewLogRoute
  '/get-started': typeof MarketingGetStartedRoute
  '/join': typeof MarketingJoinRoute
  '/login': typeof MarketingLoginRoute
  '/signup': typeof MarketingSignupRoute
  '/sso-callback': typeof MarketingSsoCallbackRoute
  '/org/$slug': typeof OrgSlugAuthenticatedRouteWithChildren
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/org/$slug/not-a-member': typeof OrgSlugNotAMemberRoute
  '/api/flags/': typeof ApiFlagsIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/org/$slug/admin': typeof OrgSlugAuthenticatedAdminRoute
  '/org/$slug/calendar': typeof OrgSlugAuthenticatedCalendarRoute
  '/org/$slug/dashboard': typeof OrgSlugAuthenticatedDashboardRoute
  '/org/$slug/goals': typeof OrgSlugAuthenticatedGoalsRoute
  '/org/$slug/insights': typeof OrgSlugAuthenticatedInsightsRoute
  '/org/$slug/log': typeof OrgSlugAuthenticatedLogRoute
  '/org/$slug/settings': typeof OrgSlugAuthenticatedSettingsRoute
  '/org/$slug/trends': typeof OrgSlugAuthenticatedTrendsRoute
  '/org/$slug/welcome': typeof OrgSlugAuthenticatedWelcomeRoute
  '/org/$slug/forgot-password': typeof OrgSlugUnauthenticatedForgotPasswordRoute
  '/org/$slug/sign-in': typeof OrgSlugUnauthenticatedSignInRoute
  '/org/$slug/sign-up': typeof OrgSlugUnauthenticatedSignUpRoute
  '/org/$slug/sso-callback': typeof OrgSlugUnauthenticatedSsoCallbackRoute
  '/org/$slug/groups/$groupId': typeof OrgSlugAuthenticatedGroupsGroupIdRoute
  '/org/$slug/journal/$journalId': typeof OrgSlugAuthenticatedJournalJournalIdRoute
  '/org/$slug/journal/new': typeof OrgSlugAuthenticatedJournalNewRoute
  '/org/$slug/groups/': typeof OrgSlugAuthenticatedGroupsIndexRoute
  '/org/$slug/journal/': typeof OrgSlugAuthenticatedJournalIndexRoute
}
export interface FileRoutesByTo {
  '/new-log': typeof NewLogRoute
  '/get-started': typeof MarketingGetStartedRoute
  '/join': typeof MarketingJoinRoute
  '/login': typeof MarketingLoginRoute
  '/signup': typeof MarketingSignupRoute
  '/sso-callback': typeof MarketingSsoCallbackRoute
  '/': typeof MarketingIndexRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/org/$slug': typeof OrgSlugIndexRoute
  '/org/$slug/not-a-member': typeof OrgSlugNotAMemberRoute
  '/api/flags': typeof ApiFlagsIndexRoute
  '/org/$slug/admin': typeof OrgSlugAuthenticatedAdminRoute
  '/org/$slug/calendar': typeof OrgSlugAuthenticatedCalendarRoute
  '/org/$slug/dashboard': typeof OrgSlugAuthenticatedDashboardRoute
  '/org/$slug/goals': typeof OrgSlugAuthenticatedGoalsRoute
  '/org/$slug/insights': typeof OrgSlugAuthenticatedInsightsRoute
  '/org/$slug/log': typeof OrgSlugAuthenticatedLogRoute
  '/org/$slug/settings': typeof OrgSlugAuthenticatedSettingsRoute
  '/org/$slug/trends': typeof OrgSlugAuthenticatedTrendsRoute
  '/org/$slug/welcome': typeof OrgSlugAuthenticatedWelcomeRoute
  '/org/$slug/forgot-password': typeof OrgSlugUnauthenticatedForgotPasswordRoute
  '/org/$slug/sign-in': typeof OrgSlugUnauthenticatedSignInRoute
  '/org/$slug/sign-up': typeof OrgSlugUnauthenticatedSignUpRoute
  '/org/$slug/sso-callback': typeof OrgSlugUnauthenticatedSsoCallbackRoute
  '/org/$slug/groups/$groupId': typeof OrgSlugAuthenticatedGroupsGroupIdRoute
  '/org/$slug/journal/$journalId': typeof OrgSlugAuthenticatedJournalJournalIdRoute
  '/org/$slug/journal/new': typeof OrgSlugAuthenticatedJournalNewRoute
  '/org/$slug/groups': typeof OrgSlugAuthenticatedGroupsIndexRoute
  '/org/$slug/journal': typeof OrgSlugAuthenticatedJournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/new-log': typeof NewLogRoute
  '/_marketing/get-started': typeof MarketingGetStartedRoute
  '/_marketing/join': typeof MarketingJoinRoute
  '/_marketing/login': typeof MarketingLoginRoute
  '/_marketing/signup': typeof MarketingSignupRoute
  '/_marketing/sso-callback': typeof MarketingSsoCallbackRoute
  '/org/$slug': typeof OrgSlugRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/org/$slug/_authenticated': typeof OrgSlugAuthenticatedRouteWithChildren
  '/org/$slug/not-a-member': typeof OrgSlugNotAMemberRoute
  '/api/flags/': typeof ApiFlagsIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/org/$slug/_authenticated/admin': typeof OrgSlugAuthenticatedAdminRoute
  '/org/$slug/_authenticated/calendar': typeof OrgSlugAuthenticatedCalendarRoute
  '/org/$slug/_authenticated/dashboard': typeof OrgSlugAuthenticatedDashboardRoute
  '/org/$slug/_authenticated/goals': typeof OrgSlugAuthenticatedGoalsRoute
  '/org/$slug/_authenticated/insights': typeof OrgSlugAuthenticatedInsightsRoute
  '/org/$slug/_authenticated/log': typeof OrgSlugAuthenticatedLogRoute
  '/org/$slug/_authenticated/settings': typeof OrgSlugAuthenticatedSettingsRoute
  '/org/$slug/_authenticated/trends': typeof OrgSlugAuthenticatedTrendsRoute
  '/org/$slug/_authenticated/welcome': typeof OrgSlugAuthenticatedWelcomeRoute
  '/org/$slug/_unauthenticated/forgot-password': typeof OrgSlugUnauthenticatedForgotPasswordRoute
  '/org/$slug/_unauthenticated/sign-in': typeof OrgSlugUnauthenticatedSignInRoute
  '/org/$slug/_unauthenticated/sign-up': typeof OrgSlugUnauthenticatedSignUpRoute
  '/org/$slug/_unauthenticated/sso-callback': typeof OrgSlugUnauthenticatedSsoCallbackRoute
  '/org/$slug/_authenticated/groups/$groupId': typeof OrgSlugAuthenticatedGroupsGroupIdRoute
  '/org/$slug/_authenticated/journal/$journalId': typeof OrgSlugAuthenticatedJournalJournalIdRoute
  '/org/$slug/_authenticated/journal/new': typeof OrgSlugAuthenticatedJournalNewRoute
  '/org/$slug/_authenticated/groups/': typeof OrgSlugAuthenticatedGroupsIndexRoute
  '/org/$slug/_authenticated/journal/': typeof OrgSlugAuthenticatedJournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new-log'
    | '/get-started'
    | '/join'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/org/$slug'
    | '/api/polar/webhook'
    | '/org/$slug/not-a-member'
    | '/api/flags/'
    | '/org/$slug/'
    | '/org/$slug/admin'
    | '/org/$slug/calendar'
    | '/org/$slug/dashboard'
    | '/org/$slug/goals'
    | '/org/$slug/insights'
    | '/org/$slug/log'
    | '/org/$slug/settings'
    | '/org/$slug/trends'
    | '/org/$slug/welcome'
    | '/org/$slug/forgot-password'
    | '/org/$slug/sign-in'
    | '/org/$slug/sign-up'
    | '/org/$slug/sso-callback'
    | '/org/$slug/groups/$groupId'
    | '/org/$slug/journal/$journalId'
    | '/org/$slug/journal/new'
    | '/org/$slug/groups/'
    | '/org/$slug/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/new-log'
    | '/get-started'
    | '/join'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/'
    | '/api/polar/webhook'
    | '/org/$slug'
    | '/org/$slug/not-a-member'
    | '/api/flags'
    | '/org/$slug/admin'
    | '/org/$slug/calendar'
    | '/org/$slug/dashboard'
    | '/org/$slug/goals'
    | '/org/$slug/insights'
    | '/org/$slug/log'
    | '/org/$slug/settings'
    | '/org/$slug/trends'
    | '/org/$slug/welcome'
    | '/org/$slug/forgot-password'
    | '/org/$slug/sign-in'
    | '/org/$slug/sign-up'
    | '/org/$slug/sso-callback'
    | '/org/$slug/groups/$groupId'
    | '/org/$slug/journal/$journalId'
    | '/org/$slug/journal/new'
    | '/org/$slug/groups'
    | '/org/$slug/journal'
  id:
    | '__root__'
    | '/_marketing'
    | '/new-log'
    | '/_marketing/get-started'
    | '/_marketing/join'
    | '/_marketing/login'
    | '/_marketing/signup'
    | '/_marketing/sso-callback'
    | '/org/$slug'
    | '/_marketing/'
    | '/api/polar/webhook'
    | '/org/$slug/_authenticated'
    | '/org/$slug/not-a-member'
    | '/api/flags/'
    | '/org/$slug/'
    | '/org/$slug/_authenticated/admin'
    | '/org/$slug/_authenticated/calendar'
    | '/org/$slug/_authenticated/dashboard'
    | '/org/$slug/_authenticated/goals'
    | '/org/$slug/_authenticated/insights'
    | '/org/$slug/_authenticated/log'
    | '/org/$slug/_authenticated/settings'
    | '/org/$slug/_authenticated/trends'
    | '/org/$slug/_authenticated/welcome'
    | '/org/$slug/_unauthenticated/forgot-password'
    | '/org/$slug/_unauthenticated/sign-in'
    | '/org/$slug/_unauthenticated/sign-up'
    | '/org/$slug/_unauthenticated/sso-callback'
    | '/org/$slug/_authenticated/groups/$groupId'
    | '/org/$slug/_authenticated/journal/$journalId'
    | '/org/$slug/_authenticated/journal/new'
    | '/org/$slug/_authenticated/groups/'
    | '/org/$slug/_authenticated/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  NewLogRoute: typeof NewLogRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  ApiPolarWebhookRoute: typeof ApiPolarWebhookRoute
  ApiFlagsIndexRoute: typeof ApiFlagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-log': {
      id: '/new-log'
      path: '/new-log'
      fullPath: '/new-log'
      preLoaderRoute: typeof NewLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/sso-callback': {
      id: '/_marketing/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof MarketingSsoCallbackRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/signup': {
      id: '/_marketing/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof MarketingSignupRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/login': {
      id: '/_marketing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MarketingLoginRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/join': {
      id: '/_marketing/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof MarketingJoinRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/get-started': {
      id: '/_marketing/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof MarketingGetStartedRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/org/$slug/': {
      id: '/org/$slug/'
      path: '/'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/api/flags/': {
      id: '/api/flags/'
      path: '/api/flags'
      fullPath: '/api/flags/'
      preLoaderRoute: typeof ApiFlagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/not-a-member': {
      id: '/org/$slug/not-a-member'
      path: '/not-a-member'
      fullPath: '/org/$slug/not-a-member'
      preLoaderRoute: typeof OrgSlugNotAMemberRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/_authenticated': {
      id: '/org/$slug/_authenticated'
      path: ''
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugAuthenticatedRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/api/polar/webhook': {
      id: '/api/polar/webhook'
      path: '/api/polar/webhook'
      fullPath: '/api/polar/webhook'
      preLoaderRoute: typeof ApiPolarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/_unauthenticated/sso-callback': {
      id: '/org/$slug/_unauthenticated/sso-callback'
      path: '/sso-callback'
      fullPath: '/org/$slug/sso-callback'
      preLoaderRoute: typeof OrgSlugUnauthenticatedSsoCallbackRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/_unauthenticated/sign-up': {
      id: '/org/$slug/_unauthenticated/sign-up'
      path: '/sign-up'
      fullPath: '/org/$slug/sign-up'
      preLoaderRoute: typeof OrgSlugUnauthenticatedSignUpRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/_unauthenticated/sign-in': {
      id: '/org/$slug/_unauthenticated/sign-in'
      path: '/sign-in'
      fullPath: '/org/$slug/sign-in'
      preLoaderRoute: typeof OrgSlugUnauthenticatedSignInRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/_unauthenticated/forgot-password': {
      id: '/org/$slug/_unauthenticated/forgot-password'
      path: '/forgot-password'
      fullPath: '/org/$slug/forgot-password'
      preLoaderRoute: typeof OrgSlugUnauthenticatedForgotPasswordRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/_authenticated/welcome': {
      id: '/org/$slug/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/org/$slug/welcome'
      preLoaderRoute: typeof OrgSlugAuthenticatedWelcomeRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/trends': {
      id: '/org/$slug/_authenticated/trends'
      path: '/trends'
      fullPath: '/org/$slug/trends'
      preLoaderRoute: typeof OrgSlugAuthenticatedTrendsRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/settings': {
      id: '/org/$slug/_authenticated/settings'
      path: '/settings'
      fullPath: '/org/$slug/settings'
      preLoaderRoute: typeof OrgSlugAuthenticatedSettingsRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/log': {
      id: '/org/$slug/_authenticated/log'
      path: '/log'
      fullPath: '/org/$slug/log'
      preLoaderRoute: typeof OrgSlugAuthenticatedLogRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/insights': {
      id: '/org/$slug/_authenticated/insights'
      path: '/insights'
      fullPath: '/org/$slug/insights'
      preLoaderRoute: typeof OrgSlugAuthenticatedInsightsRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/goals': {
      id: '/org/$slug/_authenticated/goals'
      path: '/goals'
      fullPath: '/org/$slug/goals'
      preLoaderRoute: typeof OrgSlugAuthenticatedGoalsRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/dashboard': {
      id: '/org/$slug/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/org/$slug/dashboard'
      preLoaderRoute: typeof OrgSlugAuthenticatedDashboardRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/calendar': {
      id: '/org/$slug/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/org/$slug/calendar'
      preLoaderRoute: typeof OrgSlugAuthenticatedCalendarRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/admin': {
      id: '/org/$slug/_authenticated/admin'
      path: '/admin'
      fullPath: '/org/$slug/admin'
      preLoaderRoute: typeof OrgSlugAuthenticatedAdminRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/journal/': {
      id: '/org/$slug/_authenticated/journal/'
      path: '/journal'
      fullPath: '/org/$slug/journal/'
      preLoaderRoute: typeof OrgSlugAuthenticatedJournalIndexRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/groups/': {
      id: '/org/$slug/_authenticated/groups/'
      path: '/groups'
      fullPath: '/org/$slug/groups/'
      preLoaderRoute: typeof OrgSlugAuthenticatedGroupsIndexRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/journal/new': {
      id: '/org/$slug/_authenticated/journal/new'
      path: '/journal/new'
      fullPath: '/org/$slug/journal/new'
      preLoaderRoute: typeof OrgSlugAuthenticatedJournalNewRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/journal/$journalId': {
      id: '/org/$slug/_authenticated/journal/$journalId'
      path: '/journal/$journalId'
      fullPath: '/org/$slug/journal/$journalId'
      preLoaderRoute: typeof OrgSlugAuthenticatedJournalJournalIdRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
    '/org/$slug/_authenticated/groups/$groupId': {
      id: '/org/$slug/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/org/$slug/groups/$groupId'
      preLoaderRoute: typeof OrgSlugAuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof OrgSlugAuthenticatedRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingGetStartedRoute: typeof MarketingGetStartedRoute
  MarketingJoinRoute: typeof MarketingJoinRoute
  MarketingLoginRoute: typeof MarketingLoginRoute
  MarketingSignupRoute: typeof MarketingSignupRoute
  MarketingSsoCallbackRoute: typeof MarketingSsoCallbackRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingGetStartedRoute: MarketingGetStartedRoute,
  MarketingJoinRoute: MarketingJoinRoute,
  MarketingLoginRoute: MarketingLoginRoute,
  MarketingSignupRoute: MarketingSignupRoute,
  MarketingSsoCallbackRoute: MarketingSsoCallbackRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface OrgSlugAuthenticatedRouteChildren {
  OrgSlugAuthenticatedAdminRoute: typeof OrgSlugAuthenticatedAdminRoute
  OrgSlugAuthenticatedCalendarRoute: typeof OrgSlugAuthenticatedCalendarRoute
  OrgSlugAuthenticatedDashboardRoute: typeof OrgSlugAuthenticatedDashboardRoute
  OrgSlugAuthenticatedGoalsRoute: typeof OrgSlugAuthenticatedGoalsRoute
  OrgSlugAuthenticatedInsightsRoute: typeof OrgSlugAuthenticatedInsightsRoute
  OrgSlugAuthenticatedLogRoute: typeof OrgSlugAuthenticatedLogRoute
  OrgSlugAuthenticatedSettingsRoute: typeof OrgSlugAuthenticatedSettingsRoute
  OrgSlugAuthenticatedTrendsRoute: typeof OrgSlugAuthenticatedTrendsRoute
  OrgSlugAuthenticatedWelcomeRoute: typeof OrgSlugAuthenticatedWelcomeRoute
  OrgSlugAuthenticatedGroupsGroupIdRoute: typeof OrgSlugAuthenticatedGroupsGroupIdRoute
  OrgSlugAuthenticatedJournalJournalIdRoute: typeof OrgSlugAuthenticatedJournalJournalIdRoute
  OrgSlugAuthenticatedJournalNewRoute: typeof OrgSlugAuthenticatedJournalNewRoute
  OrgSlugAuthenticatedGroupsIndexRoute: typeof OrgSlugAuthenticatedGroupsIndexRoute
  OrgSlugAuthenticatedJournalIndexRoute: typeof OrgSlugAuthenticatedJournalIndexRoute
}

const OrgSlugAuthenticatedRouteChildren: OrgSlugAuthenticatedRouteChildren = {
  OrgSlugAuthenticatedAdminRoute: OrgSlugAuthenticatedAdminRoute,
  OrgSlugAuthenticatedCalendarRoute: OrgSlugAuthenticatedCalendarRoute,
  OrgSlugAuthenticatedDashboardRoute: OrgSlugAuthenticatedDashboardRoute,
  OrgSlugAuthenticatedGoalsRoute: OrgSlugAuthenticatedGoalsRoute,
  OrgSlugAuthenticatedInsightsRoute: OrgSlugAuthenticatedInsightsRoute,
  OrgSlugAuthenticatedLogRoute: OrgSlugAuthenticatedLogRoute,
  OrgSlugAuthenticatedSettingsRoute: OrgSlugAuthenticatedSettingsRoute,
  OrgSlugAuthenticatedTrendsRoute: OrgSlugAuthenticatedTrendsRoute,
  OrgSlugAuthenticatedWelcomeRoute: OrgSlugAuthenticatedWelcomeRoute,
  OrgSlugAuthenticatedGroupsGroupIdRoute:
    OrgSlugAuthenticatedGroupsGroupIdRoute,
  OrgSlugAuthenticatedJournalJournalIdRoute:
    OrgSlugAuthenticatedJournalJournalIdRoute,
  OrgSlugAuthenticatedJournalNewRoute: OrgSlugAuthenticatedJournalNewRoute,
  OrgSlugAuthenticatedGroupsIndexRoute: OrgSlugAuthenticatedGroupsIndexRoute,
  OrgSlugAuthenticatedJournalIndexRoute: OrgSlugAuthenticatedJournalIndexRoute,
}

const OrgSlugAuthenticatedRouteWithChildren =
  OrgSlugAuthenticatedRoute._addFileChildren(OrgSlugAuthenticatedRouteChildren)

interface OrgSlugRouteChildren {
  OrgSlugAuthenticatedRoute: typeof OrgSlugAuthenticatedRouteWithChildren
  OrgSlugNotAMemberRoute: typeof OrgSlugNotAMemberRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugUnauthenticatedForgotPasswordRoute: typeof OrgSlugUnauthenticatedForgotPasswordRoute
  OrgSlugUnauthenticatedSignInRoute: typeof OrgSlugUnauthenticatedSignInRoute
  OrgSlugUnauthenticatedSignUpRoute: typeof OrgSlugUnauthenticatedSignUpRoute
  OrgSlugUnauthenticatedSsoCallbackRoute: typeof OrgSlugUnauthenticatedSsoCallbackRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugAuthenticatedRoute: OrgSlugAuthenticatedRouteWithChildren,
  OrgSlugNotAMemberRoute: OrgSlugNotAMemberRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugUnauthenticatedForgotPasswordRoute:
    OrgSlugUnauthenticatedForgotPasswordRoute,
  OrgSlugUnauthenticatedSignInRoute: OrgSlugUnauthenticatedSignInRoute,
  OrgSlugUnauthenticatedSignUpRoute: OrgSlugUnauthenticatedSignUpRoute,
  OrgSlugUnauthenticatedSsoCallbackRoute:
    OrgSlugUnauthenticatedSsoCallbackRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  NewLogRoute: NewLogRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  ApiPolarWebhookRoute: ApiPolarWebhookRoute,
  ApiFlagsIndexRoute: ApiFlagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
