/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TrendsImport } from './routes/trends'
import { Route as LogImport } from './routes/log'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TrendsRoute = TrendsImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRoute,
} as any)

const LogRoute = LogImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogImport
      parentRoute: typeof rootRoute
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/trends': typeof TrendsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/trends': typeof TrendsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/trends': typeof TrendsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/log' | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/log' | '/trends'
  id: '__root__' | '/' | '/log' | '/trends'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogRoute: typeof LogRoute
  TrendsRoute: typeof TrendsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogRoute: LogRoute,
  TrendsRoute: TrendsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/log",
        "/trends"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/log": {
      "filePath": "log.tsx"
    },
    "/trends": {
      "filePath": "trends.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
